// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCZNjoSVXnER7yT3iaOzpPBRjyAdkvPbk',
    appId: '1:564945345075:web:304411b4ed6f098234a146',
    messagingSenderId: '564945345075',
    projectId: 'project27-c4172',
    authDomain: 'project27-c4172.firebaseapp.com',
    storageBucket: 'project27-c4172.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIEKEMOdPXr0a_CP3kQvHRy3aZrTkELhI',
    appId: '1:564945345075:android:a75639678f31ae0c34a146',
    messagingSenderId: '564945345075',
    projectId: 'project27-c4172',
    storageBucket: 'project27-c4172.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCiupw-bYZnSlFXBjwkIE4zqIYXEWPcutI',
    appId: '1:564945345075:ios:0bdedd2394688cb534a146',
    messagingSenderId: '564945345075',
    projectId: 'project27-c4172',
    storageBucket: 'project27-c4172.appspot.com',
    iosBundleId: 'com.example.untitled27',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCiupw-bYZnSlFXBjwkIE4zqIYXEWPcutI',
    appId: '1:564945345075:ios:cc6a960c38071c5834a146',
    messagingSenderId: '564945345075',
    projectId: 'project27-c4172',
    storageBucket: 'project27-c4172.appspot.com',
    iosBundleId: 'com.example.untitled27.RunnerTests',
  );
}
